KATEGORI_LIST = [
    "A - Pertanian, Kehutanan dan Perikanan",
    "B - Pertambangan dan Penggalian",
    "C - Industri Pengolahan",
    "D - Pengadaan Listrik, Gas, Uap/Air Panas Dan Udara Dingin",
    "E - Treatment Air, Treatment Air Limbah, Treatment dan Pemulihan Material Sampah, dan Aktivitas Remediasi",
    "F - Konstruksi",
    "G - Perdagangan Besar Dan Eceran; Reparasi Dan Perawatan Mobil Dan Sepeda Motor",
    "H - Pengangkutan dan Pergudangan",
    "I - Penyediaan Akomodasi Dan Penyediaan Makan Minum",
    "J - Informasi Dan Komunikasi",
    "K - Aktivitas Keuangan dan Asuransi",
    "L - Real Estat",
    "M - Aktivitas Profesional, Ilmiah Dan Teknis",
    "N - Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi, Ketenagakerjaan, Agen Perjalanan dan Penunjang Usaha Lainnya",
    "O - Administrasi Pemerintahan, Pertahanan Dan Jaminan Sosial Wajib",
    "P - Pendidikan",
    "Q - Aktivitas Kesehatan Manusia Dan Aktivitas Sosial",
    "R - Kesenian, Hiburan Dan Rekreasi",
    "S - Aktivitas Jasa Lainnya",
    "T - Aktivitas Rumah Tangga Sebagai Pemberi Kerja; Aktivitas Yang Menghasilkan Barang Dan Jasa Oleh Rumah Tangga yang Digunakan untuk Memenuhi Kebutuhan Sendiri",
    "U - Aktivitas Badan Internasional Dan Badan Ekstra Internasional Lainnya"
]

DINAS_LIST = [
    "Dinas Pendidikan",
    "Dinas Kesehatan",
    "Dinas Sumber Daya Air dan Bina Marga",
    "Dinas Perumahan Rakyat dan Kawasan Permukiman Serta Pertanahan",
    "Dinas Pemadam Kebakaran dan Penyelamatan",
    "Dinas Sosial",
    "Dinas Perindustrian dan Tenaga Kerja",
    "Dinas Pemberdayaan Perempuan dan Perlindungan Anak serta Pengendalian Penduduk dan Keluarga Berencana",
    "Dinas Ketahanan Pangan dan Pertanian",
    "Dinas Lingkungan Hidup",
    "Dinas Kependudukan dan Pencatatan Sipil",
    "Dinas Perhubungan",
    "Dinas Komunikasi dan Informatika",
    "Dinas Koperasi Usaha Kecil dan Menengah dan Perdagangan",
    "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
    "Dinas Kebudayaan, Kepemudaan dan Olah Raga serta Pariwisata",
    "Dinas Perpustakaan dan Kearsipan",
    "Satuan Polisi Pamong Praja"
]

map_dinas_ke_folder = {
    "Dinas Pendidikan": "disdik",
    "Dinas Kesehatan": "dinkes",
    "Dinas Sumber Daya Air dan Bina Marga": "dsdabm",
    "Dinas Perumahan Rakyat dan Kawasan Permukiman Serta Pertanahan": "dprkpp",
    "Dinas Pemadam Kebakaran dan Penyelamatan": "dpkp",
    "Dinas Sosial": "dinsos",
    "Dinas Perindustrian dan Tenaga Kerja": "disperinaker",
    "Dinas Pemberdayaan Perempuan dan Perlindungan Anak serta Pengendalian Penduduk dan Keluarga Berencana": "dp3ap2kb",
    "Dinas Ketahanan Pangan dan Pertanian": "dkppp",
    "Dinas Lingkungan Hidup": "dlh",
    "Dinas Kependudukan dan Pencatatan Sipil": "disdukcapil",
    "Dinas Perhubungan": "dishub",
    "Dinas Komunikasi dan Informatika": "diskominfo",
    "Dinas Koperasi Usaha Kecil dan Menengah dan Perdagangan": "dinkopdag",
    "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu": "dpmptsp",
    "Dinas Kebudayaan, Kepemudaan dan Olah Raga serta Pariwisata": "disbudporapar",
    "Dinas Perpustakaan dan Kearsipan": "dispusip",
    "Satuan Polisi Pamong Praja": "satpolpp",
    "LAINNYA": "LAINNYA"
}
